%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Record of revisions:                                                    % 
%     Date           Programmer     Decription of change                  %
%     ==========     ==========     ====================                  %
%     23.02.2015     Han Rui        Original code                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%==========================================================================
% DLC_Jahresberechnen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%==========================================================================
%Dieser Programm simuliert den Jahreslastgang von Direct Load Control. Der
%Programm sucht nach den Zeitpunkt mit minimaler Last, um die Geräten zu betrieben.  
%Bitte sehe den Ablaufdiagramm auf Seite 77, Abbildung 6.12.
function [lastgang, lastgang_ohnePV]= DLC_Jahresberechnen(handles, lastprofil, lastgang_normal)
%DLC_JAHRESBERECHNEN Summary of this function goes here
%   Detailed explanation goes here

if handles.dlc_active == 0
     lastgang.heute = lastgang_normal.heute;
     lastgang_ohnePV.heute = lastgang_normal.heute+lastgang_normal.solar;
     lastgang.morgen = lastgang_normal.morgen;
     lastgang.heute_blind = lastgang_normal.heute_blind;
     lastgang.morgen_blind = lastgang_normal.morgen_blind;
     
else
     struct_sp = [];
     
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     %                   nicht DSI-fähige Elektrogeräte                   %
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     lastgang.kochen        = lastgang_normal.kochen;
     lastgang.kuehlschrank  = lastgang_normal.kuehlschrank;
     lastgang.pumpe         = lastgang_normal.pumpe;
     lastgang.entertainment = lastgang_normal.entertainment;
     lastgang.info          = lastgang_normal.info;
     lastgang.licht         = lastgang_normal.licht;
     lastgang.diverses      = lastgang_normal.diverses;
     
     lastgang.solar         = lastgang_normal.solar;
     
     lastgang.kuehlschrank_blind  = lastgang_normal.kuehlschrank_blind;
     lastgang.pumpe_blind         = lastgang_normal.pumpe_blind;
     lastgang.entertainment_blind = lastgang_normal.entertainment_blind;
     lastgang.info_blind          = lastgang_normal.info_blind;
     
     lastgang.solar_blind         = lastgang_normal.solar_blind;
     
        
     lastprofil = lastprofil+...
                  lastgang.kochen+...
                  lastgang.kuehlschrank+...
                  lastgang.pumpe+...
                  lastgang.entertainment+...
                  lastgang.info+...
                  lastgang.licht+...
                  lastgang.diverses-...
                  lastgang.solar;
     
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     %                       DSI-fähige Elektrogeräte                     %
     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%     
     % Waschmaschine
     struct_sp.waschmaschine = find(lastprofil==min(lastprofil(24:88)))-1;
     [lastgang.waschmaschine, lastgang.waschmaschine_blind] = Waschmaschinen(struct_sp.waschmaschine(1));
     lastgang.waschmaschine = lastgang.waschmaschine*handles.benutzung.waschmaschine*handles.ausstattung.waschmaschine;
     lastgang.waschmaschine_blind = lastgang.waschmaschine_blind*handles.ausstattung.waschmaschine*handles.benutzung.waschmaschine;
     
     lastgang.waeschetrockner = Waschetrockner(struct_sp.waschmaschine(1)+9);
     lastgang.waeschetrockner = lastgang.waeschetrockner*handles.benutzung.waeschetrockner*handles.ausstattung.waeschetrockner;

     lastprofil = lastprofil+...
                  lastgang.waschmaschine(1:96)+lastgang.waschmaschine(97:192)+...
                  lastgang.waeschetrockner(1:96)+lastgang.waeschetrockner(97:192);
   
     % Geschirrspüler unter Berücksichtigung der Benutzungsfrequenz
     struct_sp.geschirrspueler = find(lastprofil==min(lastprofil))-1;
     lastgang.geschirrspueler = Geschirr(struct_sp.geschirrspueler(1));
     lastgang.geschirrspueler = lastgang.geschirrspueler*handles.benutzung.geschirr*handles.ausstattung.geschirr;

     lastprofil = lastprofil+...
                  lastgang.geschirrspueler(1:96)+lastgang.geschirrspueler(97:192);
     
     
     % Heizung unter Berücksichtigung der Ausstattungsgrad
     lastgang.heizung = DLC_Heizung(handles, lastprofil, handles.anzahl_HH);
     lastprofil = lastprofil+lastgang.heizung;
    
     % Warmwasser unter Berücksichtigung der Ausstattungsgrad
     if handles.ausstattung.warmwasserspeicher==1 
         lastgang.warmwasser=DLC_Warmwasser(handles, lastprofil, handles.anzahl_HH);
     else
         lastgang.warmwasser=lastgang_normal.warmwasser(1:96);
     end
     %????????????????????????????
     
     % Berechnung der Lastgänge als Summe der einzelnen Lastgänge der
     % elektrischen Komponenten mit Gewichtungsfaktoren
     % Unterscheidung zwischen Spareinstellungen und keinen
     % Spareinstellungen
     
     if  handles.spar_active==1           
         lastgang.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                          lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                          lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                          lastgang.kochen+...
                          lastgang.kuehlschrank+...
                          lastgang.warmwasser*handles.struct_eff.warmwasser+...
                          lastgang.heizung*handles.struct_eff.heizung+...
                          lastgang.pumpe+...
                          lastgang.entertainment+...
                          lastgang.info+...
                          lastgang.licht*handles.struct_eff.licht+...
                          lastgang.diverses-...             
                          lastgang.solar;
    
         lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                                 lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                                 lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                                 lastgang.kochen+...
                                 lastgang.kuehlschrank+...
                                 lastgang.warmwasser*handles.struct_eff.warmwasser+...
                                 lastgang.heizung*handles.struct_eff.heizung+...
                                 lastgang.pumpe+...
                                 lastgang.entertainment+...
                                 lastgang.info+...
                                 lastgang.licht*handles.struct_eff.licht+...
                                 lastgang.diverses;  
         
         lastgang.morgen = lastgang.waschmaschine(97:192)*handles.struct_eff.waschmaschine+...
                           lastgang.waeschetrockner(97:192)*handles.struct_eff.waeschetrockner+...
                           lastgang.geschirrspueler(97:192)*handles.struct_eff.geschirr;
         
         lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)*handles.struct_eff.waschmaschine+...
                                lastgang.kuehlschrank_blind+...
                                lastgang.entertainment_blind+...
                                lastgang.info_blind+...
                                lastgang.solar_blind;
         
         lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192)*handles.struct_eff.waschmaschine;  
             
     else       
         lastgang.heute = lastgang.waschmaschine(1:96)+...
                          lastgang.waeschetrockner(1:96)+...
                          lastgang.geschirrspueler(1:96)+...
                          lastgang.kochen+...
                          lastgang.kuehlschrank+...
                          lastgang.warmwasser+...
                          lastgang.heizung+...
                          lastgang.pumpe+...
                          lastgang.entertainment+...
                          lastgang.info+...
                          lastgang.licht+...
                          lastgang.diverses-...
                          lastgang.solar;
                 
         lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)+...
                                 lastgang.waeschetrockner(1:96)+...
                                 lastgang.geschirrspueler(1:96)+...
                                 lastgang.kochen+...
                                 lastgang.kuehlschrank+...
                                 lastgang.warmwasser+...
                                 lastgang.heizung+...
                                 lastgang.pumpe+...
                                 lastgang.entertainment+...
                                 lastgang.info+...
                                 lastgang.licht+...
                                 lastgang.diverses;
       
         lastgang.morgen = lastgang.waschmaschine(97:192)+...
                           lastgang.waeschetrockner(97:192)+...
                           lastgang.geschirrspueler(97:192);  
        
         lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)+...
                                lastgang.kuehlschrank_blind+...
                                lastgang.entertainment_blind+...
                                lastgang.info_blind+...
                                lastgang.solar_blind;
         
         lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192);
     end
end

end

