%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Record of revisions:                                                    % 
%     Date           Programmer     Decription of change                  %
%     ==========     ==========     ====================                  %
%     22.02.2015     Han Rui        Original code                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%==========================================================================
% Haushalt Berechnen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%==========================================================================
function [lastgang, lastgang_normal] = Haushalt_Berechnen(handles, Anzahl, lastprofil)
%HAUSHALT_BERECHNEN Summary of this function goes here
%   Detailed explanation goes here

% berücksichtigen die Benutzungsmöglichkeit an einem Tag
% Waschmachine, Waschetrockner, Geschirrspuler (E-Auto)
handles=Benutzungsfrequenz(handles, Anzahl);

% berücksichtigen die Ausstattungsgrad
% Hausgräte + Solar
handles=Ausstattungsgrad(handles, Anzahl);


%% normal Lastgang
handles.initiative='no';
[lastgang_normal, handles]=Berechnen(handles, Anzahl);

% Gesamtverbrauch von einer Haushalt unter Berücksichtigung von der Effizienzsteigung
index=randi([1,100]);
if isfield(handles, 'struct_eff') && handles.struct_eff.active==1 && index<=str2num(handles.struct_eff.durchdringung)
    lastgang.single = (lastgang_normal.waschmaschine(1:96)+lastgang_normal.waschmaschine(97:192))*handles.struct_eff.waschmaschine+...% Effizienzeinsatz
                      (lastgang_normal.waeschetrockner(1:96)+lastgang_normal.waeschetrockner(97:192))*handles.struct_eff.waeschetrockner+...% Effizienzeinsatz
                      (lastgang_normal.geschirrspueler(1:96)+lastgang_normal.geschirrspueler(97:192))*handles.struct_eff.geschirr+...% Effizienzeinsatz
                      lastgang_normal.kochen+...
                      lastgang_normal.kuehlschrank+...
                      lastgang_normal.warmwasser*handles.struct_eff.warmwasser+... % Effizienzeinsatz
                      lastgang_normal.heizung*handles.struct_eff.heizung+... % Effizienzeinsatz
                      lastgang_normal.pumpe+...
                      lastgang_normal.entertainment+...
                      lastgang_normal.info+...
                      lastgang_normal.licht*handles.struct_eff.licht+... % Effizienzeinsatz
                      lastgang_normal.diverses-... % minus Photovoltaik
                      lastgang_normal.solar;   
    
    lastgang.single_blindlesitung = (lastgang_normal.waschmaschine_blind(1:96)+lastgang_normal.waschmaschine_blind(97:192))*handles.struct_eff.waschmaschine+...
                                    lastgang_normal.kuehlschrank_blind+...
                                    lastgang_normal.pumpe_blind+...
                                    lastgang_normal.entertainment_blind+...
                                    lastgang_normal.info_blind+... % cosphi ist induktiv (positive)
                                    lastgang_normal.solar_blind;
    % Effizienz Steigung Model!!!!!!!!!!!!!                                                          
    lastgang_normal.faktor_waschmaschine   = handles.struct_eff.waschmaschine;
    lastgang_normal.faktor_waeschetrockner = handles.struct_eff.waeschetrockner;
    lastgang_normal.faktor_geschirrspueler = handles.struct_eff.geschirr;
    lastgang_normal.heizung                = handles.struct_eff.heizung*lastgang_normal.heizung;
    lastgang_normal.warmwasser             = handles.struct_eff.warmwasser*lastgang_normal.warmwasser;
    lastgang_normal.licht                  = lastgang_normal.licht*handles.struct_eff.licht;
else % no Efficiency Steigung
    lastgang.single = lastgang_normal.waschmaschine(1:96)+lastgang_normal.waschmaschine(97:192)+...
                      lastgang_normal.waeschetrockner(1:96)+lastgang_normal.waeschetrockner(97:192)+...
                      lastgang_normal.geschirrspueler(1:96)+lastgang_normal.geschirrspueler(97:192)+...
                      lastgang_normal.kochen+...
                      lastgang_normal.kuehlschrank+...
                      lastgang_normal.warmwasser(1:96)+...
                      lastgang_normal.heizung+...
                      lastgang_normal.pumpe+...
                      lastgang_normal.entertainment+...
                      lastgang_normal.info+...
                      lastgang_normal.licht+...
                      lastgang_normal.diverses-...
                      lastgang_normal.solar; % minus Photovoltaik
    
    lastgang.single_blindlesitung = lastgang_normal.waschmaschine_blind(1:96)+lastgang_normal.waschmaschine_blind(97:192)+...
                                    lastgang_normal.kuehlschrank_blind+...
                                    lastgang_normal.pumpe_blind+...
                                    lastgang_normal.entertainment_blind+...
                                    lastgang_normal.info_blind;
                                    lastgang_normal.solar_blind;
    % Efffizienz Steigen!!!!!!!              
    lastgang_normal.faktor_waschmaschine=1;
    lastgang_normal.faktor_waeschetrockner=1;
    lastgang_normal.faktor_geschirrspueler=1;
end

%% Lastgang nach Price Signal
if handles.cb_ps==1
    handles.initiative='Price-Signals';
    lastgang_ps=PS_Berechnen(handles, Anzahl); % nur Waschmaschine, Wäschetrockner und Geschirrspüler
    
    % Gesamtverbrauch von einer Haushalt unter Berücksichtigung von der Effizienzsteigung
    index=randi([1,100]);
    if isfield(handles, 'struct_eff') && handles.struct_eff.active==1 && index<=str2num(handles.struct_eff.durchdringung)
        lastgang.single_ps = (lastgang_ps.waschmaschine(1:96)+lastgang_ps.waschmaschine(97:192))*handles.struct_eff.waschmaschine+... % PS_Berechnen
                             (lastgang_ps.waeschetrockner(1:96)+lastgang_ps.waeschetrockner(97:192))*handles.struct_eff.waeschetrockner+... % PS_Berechnen
                             (lastgang_ps.geschirrspueler(1:96)+lastgang_ps.geschirrspueler(97:192))*handles.struct_eff.geschirr+... % PS_Berechnen
                             lastgang_normal.kochen+...
                             lastgang_normal.kuehlschrank+...
                             lastgang_normal.warmwasser*handles.struct_eff.warmwasser+...
                             lastgang_normal.heizung*handles.struct_eff.heizung+...
                             lastgang_normal.pumpe+...
                             lastgang_normal.entertainment+...
                             lastgang_normal.info+...
                             lastgang_normal.licht+...    
                             lastgang_normal.diverses-...
                             lastgang_normal.solar; % minus Photovoltaik
        
        lastgang.single_blindlesitung_ps = (lastgang_ps.waschmaschine_blind(1:96)+lastgang_ps.waschmaschine_blind(97:192))*handles.struct_eff.waschmaschine+...
                                           lastgang_normal.kuehlschrank_blind+...
                                           lastgang_normal.pumpe_blind+...
                                           lastgang_normal.entertainment_blind+...
                                           lastgang_normal.info_blind;
                                           lastgang_normal.solar_blind;
                                       
    else % no Efficiency Steigung
        lastgang.single_ps = lastgang_ps.waschmaschine(1:96)+lastgang_ps.waschmaschine(97:192)+...
                             lastgang_ps.waeschetrockner(1:96)+lastgang_ps.waeschetrockner(97:192)+...
                             lastgang_ps.geschirrspueler(1:96)+lastgang_ps.geschirrspueler(97:192)+...
                             lastgang_normal.kochen+...
                             lastgang_normal.kuehlschrank+...
                             lastgang_normal.warmwasser(1:96)+...
                             lastgang_normal.heizung+...
                             lastgang_normal.pumpe+...
                             lastgang_normal.entertainment+...
                             lastgang_normal.info+...
                             lastgang_normal.licht+...
                             lastgang_normal.diverses-...
                             lastgang_normal.solar; % minus Photovoltaik

        lastgang.single_blindlesitung_ps = lastgang_ps.waschmaschine_blind(1:96)+lastgang_ps.waschmaschine_blind(97:192)+...
                                           lastgang_normal.kuehlschrank_blind+...
                                           lastgang_normal.pumpe_blind+...
                                           lastgang_normal.entertainment_blind+...
                                           lastgang_normal.info_blind;
                                           lastgang_normal.solar_blind;
    end
end

%% Lastgang nach Direct Load Control
if handles.cb_dlc==1
    index=randi([1,100]);
    handles.initiative='Load-Control';
    
    if index <= str2num(handles.anzahl_DLC)
        lastgang_dlc=DLC_Berechnen(handles, Anzahl, lastprofil, lastgang_normal);
        
        % Gesamtverbrauch von einer Haushalt unter Berücksichtigung von der Effizienzsteigung
        index=randi([1,100]);
        if isfield(handles, 'struct_eff') && handles.struct_eff.active==1 && index<=str2num(handles.struct_eff.durchdringung)
            lastgang.single_dlc = (lastgang_dlc.waschmaschine(1:96)+lastgang_dlc.waschmaschine(97:192))*handles.struct_eff.waschmaschine+...
                                  (lastgang_dlc.waeschetrockner(1:96)+lastgang_dlc.waeschetrockner(97:192))*handles.struct_eff.waeschetrockner+...
                                  (lastgang_dlc.geschirrspueler(1:96)+lastgang_dlc.geschirrspueler(97:192))*handles.struct_eff.geschirr+...
                                  lastgang_normal.kochen+...
                                  lastgang_normal.kuehlschrank+...
                                  handles.struct_eff.warmwasser*lastgang_dlc.warmwasser+...
                                  handles.struct_eff.heizung*lastgang_dlc.heizung+...
                                  lastgang_normal.pumpe+...
                                  lastgang_normal.entertainment+...
                                  lastgang_normal.info+...
                                  lastgang_normal.licht+...
                                  lastgang_normal.diverses-...
                                  lastgang_normal.solar; % minus Photovoltaik  
            
            lastgang.single_blindlesitung_dlc = (lastgang_dlc.waschmaschine_blind(1:96)+lastgang_dlc.waschmaschine_blind(97:192))*handles.struct_eff.waschmaschine+...
                                                lastgang_normal.kuehlschrank_blind+...
                                                lastgang_normal.pumpe_blind+...
                                                lastgang_normal.entertainment_blind+...
                                                lastgang_normal.info_blind;
                                                lastgang_normal.solar_blind;
        else
            lastgang.single_dlc = lastgang_dlc.waschmaschine(1:96)+lastgang_dlc.waschmaschine(97:192)+...
                                  lastgang_dlc.waeschetrockner(1:96)+lastgang_dlc.waeschetrockner(97:192)+...
                                  lastgang_dlc.geschirrspueler(1:96)+lastgang_dlc.geschirrspueler(97:192)+...
                                  lastgang_normal.kochen+...
                                  lastgang_normal.kuehlschrank+...
                                  lastgang_dlc.warmwasser+...
                                  lastgang_dlc.heizung+...
                                  lastgang_normal.pumpe+...
                                  lastgang_normal.entertainment+...
                                  lastgang_normal.info+...
                                  lastgang_normal.licht+...
                                  lastgang_normal.diverses-...
                                  lastgang_normal.solar; % minus Photovoltaik
              
            lastgang.single_blindlesitung_dlc = lastgang_dlc.waschmaschine_blind(1:96)+lastgang_dlc.waschmaschine_blind(97:192)+...
                                                lastgang_normal.kuehlschrank_blind+...
                                                lastgang_normal.pumpe_blind+...
                                                lastgang_normal.entertainment_blind+...
                                                lastgang_normal.info_blind;
                                                lastgang_normal.solar_blind;
        end
    else
        lastgang.single_dlc = lastgang.single;
        lastgang.single_blindlesitung_dlc = lastgang.single_blindlesitung;
    end
end
%%
end

