%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Record of revisions:                                                    % 
%     Date           Programmer     Decription of change                  %
%     ==========     ==========     ====================                  %
%     16.03.2015     Han Rui        Original code                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%==========================================================================
% Jahresberechnen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%==========================================================================
% In diesem Programm werden die Jahreslastgänge aller Haushaltgeräte
% simuliert.
function [lastgang, lastgang_ohnePV, handles]=Jahresberechnen(handles, tag)
%JAHRESBERECHNEN Summary of this function goes here
%   Detailed explanation goes here
 
 [struct_sp, handles] = startpunkt(handles);

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Waschmaschine                              %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.waschmaschine, lastgang.waschmaschine_blind] = Waschmaschinen(struct_sp.waschmaschine);
 lastgang.waschmaschine = lastgang.waschmaschine*handles.ausstattung.waschmaschine*handles.benutzung.waschmaschine;
 lastgang.waschmaschine_blind = lastgang.waschmaschine_blind*handles.ausstattung.waschmaschine*handles.benutzung.waschmaschine;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Wäschetrockner                             %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.waeschetrockner = Waschetrockner(struct_sp.waschmaschine+randi([7,8]));      % randi([7,8])
 lastgang.waeschetrockner = lastgang.waeschetrockner*handles.ausstattung.waeschetrockner*handles.benutzung.waeschetrockner; 
 
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Geschirrspüler                             %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.geschirrspueler = Geschirr(struct_sp.geschirrspueler);
 lastgang.geschirrspueler = lastgang.geschirrspueler*handles.ausstattung.geschirr*handles.benutzung.geschirr;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                                 Kochen                                 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.kochen = Kochen(handles,handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                              Kühlschrank                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
 [lastgang.kuehlschrank, lastgang.kuehlschrank_blind] = Kuehlschrank(handles, handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                              Warmwasser                                %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.warmwasser = Warmwasser_Nachtspeicher(handles,handles.anzahl_HH,struct_sp.warmwasser);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Elektroheizung                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.heizung = Elektroheizung(handles, handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Kreiselpumpe                                 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.pumpe, lastgang.pumpe_blind] = Jahres_Kreiselpumpe(handles,handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Entertainment                                %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.entertainment, lastgang.entertainment_blind] = Entertainment(handles,handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Informatik                                   %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.info, lastgang.info_blind] = Informatik(handles, handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Licht                                      %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.licht = Licht(handles,handles.anzahl_HH);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Diverse                                    %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.diverses = Diverse(handles, handles.anzahl_HH);

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Photovoltaic                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.solar, lastgang.cosphi, lastgang.solar_blind] = solarenergie(handles, tag);
 
 
 % Gesamtverbrauch von einer Haushalt unter Berücksichtigung von der Effizienzsteigung  
 if  handles.spar_active==1
        
     lastgang.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                      lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                      lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                      lastgang.kochen+...
                      lastgang.kuehlschrank+...
                      lastgang.warmwasser*handles.struct_eff.warmwasser+...
                      lastgang.heizung*handles.struct_eff.heizung+...
                      lastgang.pumpe+...
                      lastgang.entertainment+...
                      lastgang.info+...
                      lastgang.licht*handles.struct_eff.licht+...
                      lastgang.diverses-...  % minus Photovoltaik
                      lastgang.solar;
         
     lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                             lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                             lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                             lastgang.kochen+...
                             lastgang.kuehlschrank+...
                             lastgang.warmwasser*handles.struct_eff.warmwasser+...
                             lastgang.heizung*handles.struct_eff.heizung+...
                             lastgang.pumpe+...
                             lastgang.entertainment+...
                             lastgang.info+...
                             lastgang.licht*handles.struct_eff.licht+...
                             lastgang.diverses;
                         
     % Es gibt eine Möglichkeit dass Anfangszeit ist zwischen zwei Tage      
     lastgang.morgen = lastgang.waschmaschine(97:192)*handles.struct_eff.waschmaschine+...
                       lastgang.waeschetrockner(97:192)*handles.struct_eff.waeschetrockner+...
                       lastgang.geschirrspueler(97:192)*handles.struct_eff.geschirr;
     
     lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)*handles.struct_eff.waschmaschine+...
                            lastgang.kuehlschrank_blind+...
                            lastgang.pumpe_blind+... 
                            lastgang.entertainment_blind+...
                            lastgang.info_blind+...
                            lastgang.solar_blind;
         
     lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192)*handles.struct_eff.waschmaschine;
          
 else % Keine Effizienz Steigung
     
     lastgang.heute = lastgang.waschmaschine(1:96)+...
                      lastgang.waeschetrockner(1:96)+...
                      lastgang.geschirrspueler(1:96)+...
                      lastgang.kochen+...
                      lastgang.kuehlschrank+...
                      lastgang.warmwasser+...
                      lastgang.heizung+...
                      lastgang.pumpe+...
                      lastgang.entertainment+...
                      lastgang.info+...
                      lastgang.licht+...
                      lastgang.diverses-...
                      lastgang.solar;
    
     lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)+...
                             lastgang.waeschetrockner(1:96)+...
                             lastgang.geschirrspueler(1:96)+...
                             lastgang.kochen+...
                             lastgang.kuehlschrank+...
                             lastgang.warmwasser+...
                             lastgang.heizung+...
                             lastgang.pumpe+...
                             lastgang.entertainment+...
                             lastgang.info+...
                             lastgang.licht+...
                             lastgang.diverses;
    
     lastgang.morgen = lastgang.waschmaschine(97:192)+...
                       lastgang.waeschetrockner(97:192)+...
                       lastgang.geschirrspueler(97:192);
    
     lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)+...
                            lastgang.kuehlschrank_blind+...
                            lastgang.pumpe_blind+...
                            lastgang.entertainment_blind+...
                            lastgang.info_blind+...
                            lastgang.solar_blind;
         
     lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192);
    
 end
    
 end



