%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Record of revisions:                                                    % 
%     Date           Programmer     Decription of change                  %
%     ==========     ==========     ====================                  %
%     23.02.2015     Han Rui        Original code                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%==========================================================================
% Preis Signal Jahresberechnen %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%==========================================================================
%Dieser Programm simuliert den Lastgang von TOU-Tarifen. Der
%Programm bestimmt den Startzeitpunkt von Waschmaschinen und Geschirrspüler
%stochastisch, unter Berücksichtigung der TOU-Tarifen und normale Häufigkeitsverteilung. 
%Für Detail bitte sehen Seite 69-70.
function [lastgang, lastgang_ohnePV]=PS_Jahresberechnen(handles, lastgang_normal)
%JAHRESBERECHNEN Summary of this function goes here
%   Detailed explanation goes here
 
 [struct_sp, handles] = startpunkt(handles);
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Waschmaschine                              %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 [lastgang.waschmaschine, lastgang.waschmaschine_blind] = Waschmaschinen(struct_sp.waschmaschine);
 lastgang.waschmaschine = lastgang.waschmaschine*handles.ausstattung.waschmaschine*handles.benutzung.waschmaschine;
 lastgang.waschmaschine_blind = lastgang.waschmaschine_blind*handles.ausstattung.waschmaschine*handles.benutzung.waschmaschine;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Wäschetrockner                             %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.waeschetrockner = Waschetrockner(struct_sp.waschmaschine+9);
 lastgang.waeschetrockner = lastgang.waeschetrockner*handles.ausstattung.waeschetrockner*handles.benutzung.waeschetrockner;

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Geschirrspüler                             %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.geschirrspueler = Geschirr(struct_sp.geschirrspueler);
 lastgang.geschirrspueler = lastgang.geschirrspueler*handles.ausstattung.geschirr*handles.benutzung.geschirr;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                                 Kochen                                 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.kochen = lastgang_normal.kochen;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                              Kühlschrank                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.kuehlschrank = lastgang_normal.kuehlschrank;
 lastgang.kuehlschrank_blind = lastgang_normal.kuehlschrank_blind;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                              Warmwasser                                %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
 lastgang.warmwasser = lastgang_normal.warmwasser;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Elektroheizung                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.heizung = lastgang_normal.heizung;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Kreiselpumpe                                 %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.pumpe = lastgang_normal.pumpe;
 lastgang.pumpe_blind = lastgang_normal.pumpe_blind;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Entertainment                                %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
 lastgang.entertainment = lastgang_normal.entertainment;
 lastgang.entertainment_blind = lastgang_normal.entertainment_blind;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                           Informatik                                   %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.info = lastgang_normal.info;
 lastgang.info_blind = lastgang_normal.info_blind;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Licht                                      %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.licht = lastgang_normal.licht;
  
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Diverse                                    %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.diverses = lastgang_normal.diverses;
 
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 %                             Photovoltaic                               %
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 lastgang.solar = lastgang_normal.solar;
 lastgang.solar_blind = lastgang_normal.solar_blind;   
 
 if  handles.spar_active==1
        
     lastgang.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                      lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                      lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                      lastgang.kochen+...
                      lastgang.kuehlschrank+...
                      lastgang.warmwasser*handles.struct_eff.warmwasser+...
                      lastgang.heizung*handles.struct_eff.heizung+...
                      lastgang.pumpe+...
                      lastgang.entertainment+...
                      lastgang.info+...
                      lastgang.licht*handles.struct_eff.licht+...
                      lastgang.diverses-...
                      lastgang.solar;
     
     lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)*handles.struct_eff.waschmaschine+...
                             lastgang.waeschetrockner(1:96)*handles.struct_eff.waeschetrockner+...
                             lastgang.geschirrspueler(1:96)*handles.struct_eff.geschirr+...
                             lastgang.kochen+...
                             lastgang.kuehlschrank+...
                             lastgang.warmwasser*handles.struct_eff.warmwasser+...
                             lastgang.heizung*handles.struct_eff.heizung+...
                             lastgang.pumpe+...
                             lastgang.entertainment+...
                             lastgang.info+...
                             lastgang.licht*handles.struct_eff.licht+...
                             lastgang.diverses;    

     lastgang.morgen = lastgang.waschmaschine(97:192)*handles.struct_eff.waschmaschine+...
                       lastgang.waeschetrockner(97:192)*handles.struct_eff.waeschetrockner+...
                       lastgang.geschirrspueler(97:192)*handles.struct_eff.geschirr;
     
     lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)*handles.struct_eff.waschmaschine+...
                            lastgang.kuehlschrank_blind+...
                            lastgang.pumpe_blind+...
                            lastgang.entertainment_blind+...
                            lastgang.info_blind+...
                            lastgang.solar_blind;
         
     lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192)*handles.struct_eff.waschmaschine;     
          
 else
     
     lastgang.heute = lastgang.waschmaschine(1:96)+...
                      lastgang.waeschetrockner(1:96)+...
                      lastgang.geschirrspueler(1:96)+...
                      lastgang.kochen+...
                      lastgang.kuehlschrank+...
                      lastgang.warmwasser+...
                      lastgang.heizung+...
                      lastgang.pumpe+...
                      lastgang.entertainment+...
                      lastgang.info+...
                      lastgang.licht+...
                      lastgang.diverses-...
                      lastgang.solar;
  
     lastgang_ohnePV.heute = lastgang.waschmaschine(1:96)+...
                             lastgang.waeschetrockner(1:96)+...
                             lastgang.geschirrspueler(1:96)+...
                             lastgang.kochen+...
                             lastgang.kuehlschrank+...
                             lastgang.warmwasser+...
                             lastgang.heizung+...
                             lastgang.pumpe+...
                             lastgang.entertainment+...
                             lastgang.info+...
                             lastgang.licht+...       
                             lastgang.diverses;
    
     lastgang.morgen = lastgang.waschmaschine(97:192)+...
                       lastgang.waeschetrockner(97:192)+...
                       lastgang.geschirrspueler(97:192);
    
     lastgang.heute_blind = lastgang.waschmaschine_blind(1:96)+...
                            lastgang.kuehlschrank_blind+...
                            lastgang.pumpe_blind+...
                            lastgang.entertainment_blind+...
                            lastgang.info_blind+...
                            lastgang.solar_blind;
         
     lastgang.morgen_blind = lastgang.waschmaschine_blind(97:192);
    
 end
    
 end

